spring:
  application:
    name: scorpio-redis-provider

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: redis://127.0.0.1:6379
  application:
    qos-port: 2224
  provider:
    timeout: 5000
  scan:
    base-packages: com.zhouByte
